name: build

on:
  pull_request:
    types: [synchronize, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - run: npm install
      - run: npm build
      